### PR TITLE
docs: update jetbrains sponsor logo

### PR DESCRIPTION
**Pull request by niklas-wortmann**
We updated our logo for JetBrains IDEs. I hope it is ok that I increased the size, it kinda looked weird next to the others. Hope it wasn't associated with a certain sponsor package or something. If so, I am more than happy to revert that change

### CODE REVIEW

**Comment by zkochan** [comment]
This will only look good in the dark theme (which is off by default).

**Comment by niklas-wortmann** [comment]
@zkochan that's a good point, I will test a couple different logo variation. Thanks!

**Comment by zkochan** [comment]
How did you manage to make the logo change its color in the different theme?

**Comment by niklas-wortmann** [comment]
svg has support for the style attribute so I just ship some basic styles with the SVG 
image

**Pull request merged**
