### PR TITLE
make it clearer that `packageExtensions` can only be set at root package

### PR DESCRIPTION
**Pull request by ztl8702**
# Context

I spent quite a bit of time debugging my package.json, until I found this comment https://github.com/pnpm/pnpm/issues/4097#issuecomment-1044454589

I think this caveat should be made clearer in the documentation.

### CODE REVIEW

**Comment by ztl8702** [comment]
There are other sections in this file, e.g. https://pnpm.io/package_json#pnpmneverbuiltdependencies, let me know if I should add the same note to those sections too.

**Comment by zkochan** [comment]
All those fields should be in the root of the workspace. I don't think you should duplicated the info to all fields. Just put it at the top of the file maybe.

**Comment by Toxaris** [comment]
Some documentation that I need to apply these settings in the root package.json would have helped me today with converting a running example to a monorepo setup with pnpm workspaces. Would be great to see this merged!

**Comment by Toxaris** [comment]
On second thought, in addition to documenting this, could `pnpm` have warned me about my ineffective `pnpm` setup in a non-root package.json? Something like:

```
$ pnpm install
WARN: It seems that you are putting pnpm configuration into `frontend/package.json` but pnpm will only read configuration from the root package.json file.
```

**Comment by zkochan** [comment]
adding a warning sounds good.

**Pull request closed without merging**
