### PR TITLE
docs: environment variables

### PR DESCRIPTION
**Pull request by KSXGitHub**
fixes https://github.com/pnpm/pnpm/issues/6776

### CODE REVIEW

**Comment by KSXGitHub** [comment]
@zkochan Is this what you meant? https://github.com/pnpm/pnpm.io/pull/430/commits/d66dfc2481c59f4035373f08a976b1a6f9fad8b5

**Comment by zkochan** [comment]
yes

**Comment by KSXGitHub** [comment]
So, can this be merged?

**Comment by zkochan** [comment]
I'll check later

**Pull request merged**
